# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('posicao', models.CharField(choices=[('ATA', 'Atacante'), ('MEI', 'Meio-Campo'), ('ZAG', 'Zagueiro'), ('LAT', 'Lateral')], max_length=3)),
                ('ritmo', models.IntegerField()),
                ('chute', models.IntegerField()),
                ('passe', models.IntegerField()),
                ('drible', models.IntegerField()),
                ('defesa', models.IntegerField()),
                ('fisico', models.IntegerField()),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogador.Clube')),
            ],
        ),
    ]
