# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
